### ISSUE TITLE
.tar.gz archive remains in the image

### ISSUE THREAD

**Issue by sideeffffect** [chainguard-images/jdk#4]
The image contains the archive `OpenJDK17U-jdk_x64_alpine-linux_hotspot_17.0.4_8.tar.gz` under `/usr`.
This is unnecessary and bloats the image size (by 190 MB).

**Comment by amouat** [comment]
Thanks!

There's still quite a lot to do in this image, it's still very much a wip.

**Comment by amouat** [comment]
This should be fixed in the new wolfi based images.
