### ISSUE TITLE
JDK/JRE 11 support

### ISSUE THREAD

**Issue by Footur** [chainguard-images/jdk#6]
Thank you for your awesome work on Wolfi.

Many Java application are still depending on Java 11. It would be great if there could be a container image with JDK/JRE 11 as well.

**Comment by amouat** [comment]
Sorry, I forgot to update this issue.

There is an openjdk-11 image: cgr.dev/chainguard/jdk:openjdk-11

We're in the middle of migrating to a new repo system, at which point we will also update docs and make tags etc clearer.
